[package]
name = "wasm-server-runner"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = "0.2"

wasm-bindgen-cli-support = "0.2"

axum = { version = "0.2", default-features = false }
tokio = { version = "1.11", default-features = false, features = ["rt-multi-thread"] }
tower-http = { version = "0.1", features = ["trace"] }
tower = "0.4"
fastrand = "1.5"
