[package]
name = "wasm-server-runner"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

wasm-bindgen-cli-support = "0.2"

axum = { version = "0.4", default-features = false, features = ["http1"] }
tokio = { version = "1.11", default-features = false, features = ["rt-multi-thread"] }
tower-http = { version = "0.2", features = ["fs", "trace"] }
tower = "0.4"
fastrand = "1.5"
